<?xml version="1.0" ?><xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"><xsl:output method="text" indent="no"/><xsl:template match="/data"><![CDATA[<div data-wrapper=true style="font-family:'Segoe UI','Helvetica Neue',sans-serif;font-size:9pt;"><div><span style="font-size:12pt;"><span style="font-family:'Times New Roman',Times,serif;">To: [primaryContactName];[secondaryContactName];[parentCompanyPrimaryName]</span></span></div>
<div><span style="font-size:12pt;"><span style="font-family:'Times New Roman',Times,serif;">[siteName]</span></span></div>
<div>&#160;</div>
<div><span style="font-size:12pt;"><span><span style="font-family:&quot;Times New Roman&quot;,serif;">From: Engineering Services, Transportation of Dangerous Goods, Transport Canada</span></span></span></div>
<div>&#160;</div>
<div><span style="font-size:12pt;"><span class=keyboardFocusClass><span style="font-family:&quot;Times New Roman&quot;,serif;">You registration under number [operationName] has been closed. You are no longer registered, and any registered mark associated to this registration, shall no longer be applied.</span></span></span></div>
<div><br><span style="font-size:12pt;"><span><span style="font-family:&quot;Times New Roman&quot;,serif;">Service Request ID number: [serviceRequestId]<br>Service Request Type: [serviceRequestType]<br>Registration Type: [registrationType]<br>Standard: [standard]<br>Company Name: [siteName]<br>Site address: [siteAddress]</span></span></span><br>&#160;</div>
<div>&#160;</div>
<div>&#160;</div>
<div><span style="font-size:12pt;"><span><span style="font-family:&quot;Times New Roman&quot;,serif;">----------------------------------------------------------</span></span></span></div>
<div>&#160;</div>
<div>&#160;</div>
<div><span lang=FR-CA style="font-size:12.0pt;"><span style="font-family:&quot;Times New Roman&quot;,serif;">À :&#160;</span></span><span style="font-size:12pt;"><span style="font-family:'Times New Roman',Times,serif;">[primaryContactName];[secondaryContactName];[parentCompanyPrimaryName]</span></span></div>
<div><span style="font-size:12pt;"><span style="font-family:'Times New Roman',Times,serif;">[siteName]</span></span></div>
<div>&#160;</div>
<div><span style="font-size:12pt;"><span style="font-family:Arial,sans-serif;"><span lang=FR-CA style="font-family:&quot;Times New Roman&quot;,serif;">De : Services d'ingénierie, Transport des marchandises dangereuses, Transports Canada</span></span></span><br><br><br><span style="font-size:12pt;"><span style="font-family:Arial,sans-serif;"><span lang=FR-CA style="font-family:&quot;Times New Roman&quot;,serif;">Objet : Fermeture de l'inscription</span></span></span></div>
<div>&#160;</div>
<div><div><span style="font-size:12pt;"><span style="font-family:'Times New Roman',Times,serif;">Votre inscription sous le numéro [</span><span><span style="font-family:&quot;Times New Roman&quot;,serif;">operationName</span></span><span style="font-family:'Times New Roman',Times,serif;">] a été fermer. Vous n'êtes plus inscrit, et toute marque enregistrée associée à cet inscription, ne doit plus être appliquée.&#160;</span></span></div>
<div>&#160;</div>
<div><span style="font-size:12pt;" class=keyboardFocusClass><span style="font-family:'Times New Roman',Times,serif;">Numéro de demande de service: [serviceRequestId]</span><br><span style="font-family:'Times New Roman',Times,serif;">Type de demande de service:[serviceRequestType]</span><br><span style="font-family:'Times New Roman',Times,serif;">Type d’inscription: [registrationType]</span><br><span style="font-family:'Times New Roman',Times,serif;">Norme: [standard]</span><br><span style="font-family:'Times New Roman',Times,serif;">Nom d’entreprise: [siteName]</span><br><span style="font-family:'Times New Roman',Times,serif;">Localisation: [siteAddress]</span></span></div></div></div>]]></xsl:template></xsl:stylesheet>