<?xml version="1.0" ?><xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"><xsl:output method="text" indent="no"/><xsl:template match="/data"><![CDATA[<div data-wrapper="true" style="font-family:'Segoe UI','Helvetica Neue',sans-serif; font-size:9pt"><div><span style="font-size:12pt"><span style="font-family:'Times New Roman',Times,serif">To: [primaryContactName]</span></span></div>
<div><span style="font-size:12pt"><span style="font-family:'Times New Roman',Times,serif">[siteName]</span></span></div>
<div>&nbsp;</div>
<div><span style="font-size:12pt"><span><span style="font-family:&quot;Times New Roman&quot;,serif">From: Engineering Services, Transportation of Dangerous Goods, Transport Canada</span></span></span><br>&nbsp;</div>
<div><span style="font-size:12pt"><span><span style="font-family:&quot;Times New Roman&quot;,serif">Following the latest information we have received on [submissionDate], your Registration number [operationName] has been closed. </span></span></span></div>
<div>&nbsp;</div>
<div><span style="font-size:12pt"><span><span style="font-family:&quot;Times New Roman&quot;,serif">Your facility located at [siteAddress] is no longer registered as [serviceRequestType]. Any registered mark associated to this registration<strong>,</strong> shall no longer be applied.</span></span></span><br><br><span style="font-size:12pt"><span><span style="font-family:&quot;Times New Roman&quot;,serif">Please do not hesitate to contact us should you have any further questions.</span></span></span><br><br><span style="font-size:12pt"><span><span style="font-family:&quot;Times New Roman&quot;,serif">Sincerely,</span></span></span><br><br><span style="font-size:12pt"><span><span style="font-family:&quot;Times New Roman&quot;,serif">Engineering Services</span></span></span></div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div><span style="font-size:12pt"><span><span style="font-family:&quot;Times New Roman&quot;,serif">----------------------------------------------------------</span></span></span></div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div><span lang="FR-CA" style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif">À :&nbsp;</span></span><span style="font-size:12pt"><span style="font-family:'Times New Roman',Times,serif">[primaryContactName]</span></span></div>
<div><span style="font-size:12pt"><span style="font-family:'Times New Roman',Times,serif">[siteName]</span></span></div>
<div>&nbsp;</div>
<div><span style="font-size:12pt"><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">De : Services d'ingénierie, Transport des marchandises dangereuses, Transports Canada</span></span></span><br><br><br><span style="font-size:12pt"><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">Objet : Fermeture de l'inscription</span></span></span></div>
<div>&nbsp;</div>
<div><span style="font-size:12pt"><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">À la suite des derniers renseignements que nous avons reçus le [</span></span><span><span style="font-family:&quot;Times New Roman&quot;,serif">submissionDate</span></span><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">], votre inscription portant le numéro [</span></span><span><span style="font-family:&quot;Times New Roman&quot;,serif">operationName</span></span><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">] a été fermé. Votre installation située au [</span></span><span><span style="font-family:&quot;Times New Roman&quot;,serif">siteAddress</span></span><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">] n'est plus enregistrée en tant que [</span></span><span><span style="font-family:&quot;Times New Roman&quot;,serif">serviceRequestType</span></span><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">]. Toute marque enregistrée associée à cette inscription ne sera plus appliquée.</span></span></span><br><br><span style="font-size:12pt"><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">N'hésitez pas à nous contacter si vous avez d'autres questions.</span></span></span><br><br><span style="font-size:12pt"><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">Veuillez agréer, Madame, Monsieur, l'expression de nos sentiments distingués,</span></span></span><br><br><span style="font-size:12pt"><span style="font-family:Arial,sans-serif"><span lang="FR-CA" style="font-family:&quot;Times New Roman&quot;,serif">Services d'ingénierie</span></span></span></div>
<div>&nbsp;</div></div>]]></xsl:template></xsl:stylesheet>